In [11]:
import pandas as pd
import numpy as np

In [12]:
volumCP = pd.read_csv('volumenes_asegCP.csv')
volumCogConVar= pd.read_csv('volumenes_asegCogConVar.csv')
volumNCN = pd.read_csv('volumenes_asegNCN.csv')
volumADNI = pd.read_csv('volumenes_asegADNI.csv')

csvcp=pd.read_csv('/data/Lautaro/Documentos/BrainAgeCOVID/DATOS/ResumenRespuestasACTUALIZADO.csv')
csvCogConVar=pd.read_csv('/data/Lautaro/Documentos/BrainAgeCOVID/DATOS/CogConVarparticipants.csv',sep='\t')
csvNCN=pd.read_csv('/data/Lautaro/Documentos/BrainAgeCOVID/DATOS/NCNparticipants.csv',sep='\t')
csvadni=pd.read_csv('/data/Lautaro/Documentos/BrainAgeCOVID/DATOS/ADNI_3_T1_3_13_2023.csv')

In [13]:
#primero con CPstats
csvcp = csvcp[['ID', 'Edad','Grupo','Genero']]
csvcp.rename(columns={'ID': 'participant', 'Edad': 'Age', 'Grupo': 'dx', 'Genero': 'sex'}, inplace=True)
csvcp['dx'] = csvcp['dx'].replace({'CONTROL': 'UNSAM_CN', 'COVID': 'UNSAM_LC'})
csvcp['sex'] = csvcp['sex'].replace({'F': 'Female', 'M': 'Male'})
volumCP.rename(columns={'SubjectID': 'participant'},inplace=True)
brainchartCP = pd.merge(csvcp, volumCP, on='participant', how='inner')
brainchartCP['age_days'] = brainchartCP['Age'] * 365.245+280
brainchartCP['study']='UNSAM_LC'
brainchartCP['fs_version']=np.nan
brainchartCP['country']=np.nan
brainchartCP['run']=1
brainchartCP['session']=1

In [14]:
#lo mismo con CogConVar
csvCogConVar = csvCogConVar[['participant_id', 'age', 'sex']]
csvCogConVar.rename(columns={'participant_id': 'participant', 'age': 'Age'}, inplace=True)
csvCogConVar['dx']='RRIB_CN'
csvCogConVar['sex'].replace({'m':'Male', 'f':'Female'}, inplace=True)
volumCogConVar.rename(columns={'SubjectID': 'participant'},inplace=True)
volumCogConVar['participant'] = volumCogConVar['participant'].str.replace('_T1w', '', regex=True)
brainchartCogConVar = pd.merge(csvCogConVar, volumCogConVar, on='participant', how='inner')
brainchartCogConVar['age_days'] = brainchartCogConVar['Age'] * 365.245+280
brainchartCogConVar['study']='RRIB'
brainchartCogConVar['fs_version']=np.nan
brainchartCogConVar['country']=np.nan
brainchartCogConVar['run']=1
brainchartCogConVar['session']=1
brainchartCogConVar['participant'] =  brainchartCogConVar['participant'] + '_RRIB'

/tmp/ipykernel_1315664/1051422359.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csvCogConVar['sex'].replace({'m':'Male', 'f':'Female'}, inplace=True)

In [15]:
csvNCN= csvNCN[['participant_id', 'age', 'sex']]
csvNCN.rename(columns={'participant_id': 'participant', 'age': 'Age'}, inplace=True)
csvNCN['dx']='JUK_CN'
csvNCN['sex'].replace({'M':'Male', 'F':'Female'}, inplace=True)
volumNCN.rename(columns={'SubjectID': 'participant'},inplace=True)
volumNCN['participant'] = volumNCN['participant'].str.replace('_T1w', '', regex=True)
brainchartNCN = pd.merge(csvNCN, volumNCN, on='participant', how='inner')
brainchartNCN['age_days'] = brainchartNCN['Age'] * 365.245+280
brainchartNCN['study']='JUK'
brainchartNCN['fs_version']=np.nan
brainchartNCN['country']=np.nan
brainchartNCN['run']=1
brainchartNCN['session']=1
brainchartNCN['participant'] =  brainchartNCN['participant'] + '_JUK'

/tmp/ipykernel_1315664/413319574.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csvNCN['sex'].replace({'M':'Male', 'F':'Female'}, inplace=True)

In [16]:
csvadni=csvadni[['ID', 'Age','Group','Sex']]
csvadni.rename(columns={'ID': 'participant', 'Group': 'dx', 'Sex':'sex'}, inplace=True)
csvadni['sex'].replace({'F':'Female', 'M':'Male'}, inplace=True)
volumADNI.rename(columns={'SubjectID': 'participant'},inplace=True)
brainchartADNI = pd.merge(csvadni, volumADNI, on='participant', how='inner')
brainchartADNI['age_days'] = brainchartADNI['Age'] * 365.245+280
brainchartADNI['study']='ADNI'
brainchartADNI['fs_version']=np.nan
brainchartADNI['country']=np.nan
brainchartADNI['run']=1
brainchartADNI['session']=1
#separar los grupos de control de enfermedad
brainchartADNI['dx'] = brainchartADNI['dx'].replace({'CN': 'ADNI_CN', 'AD': 'ADNI_AD_MCI', 'MCI': 'ADNI_AD_MCI','SMC': 'ADNI_AD_MCI','EMCI': 'ADNI_AD_MCI','LMCI': 'ADNI_AD_MCI'})

/tmp/ipykernel_1315664/4004369655.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  csvadni['sex'].replace({'F':'Female', 'M':'Male'}, inplace=True)

In [17]:
concatbrainchart = pd.concat([brainchartCP, brainchartCogConVar, brainchartNCN, brainchartADNI], ignore_index=True)

In [18]:
#guardar el CSV
concatbrainchart.to_csv('brainchart.csv', index=False)

In [19]:
concatbrainchart

,participant,Age,dx,sex,GMV,WMV,sGMV,Ventricles,age_days,study,fs_version,country,run,session
0,CP0001,34,UNSAM_CN,Female,481035.912509,492292.0,61045.0,12090.0,12698.330,UNSAM_LC,NaN,NaN,1,1
1,CP0002,50,UNSAM_CN,Female,419939.579669,446226.0,57034.0,20693.0,18542.250,UNSAM_LC,NaN,NaN,1,1
2,CP0003,53,UNSAM_CN,Female,408157.323101,391774.0,49427.0,31380.0,19637.985,UNSAM_LC,NaN,NaN,1,1
3,CP0004,59,UNSAM_CN,Male,487378.935857,572069.0,61433.0,23116.0,21829.455,UNSAM_LC,NaN,NaN,1,1
4,CP0006,39,UNSAM_CN,Male,505261.983270,514120.0,66685.0,22381.0,14524.555,UNSAM_LC,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,006_S_6441_I1214051,90,ADNI_AD_MCI,Male,443145.507020,396294.0,50818.0,65439.0,33152.050,ADNI,NaN,NaN,1,1
670,007_S_6515_I1029029,90,ADNI_CN,Female,423753.496483,364006.0,49393.0,42324.0,33152.050,ADNI,NaN,NaN,1,1
671,005_S_0610_I906096,90,ADNI_CN,Male,390592.719830,326882.0,52249.0,63862.0,33152.050,ADNI,NaN,NaN,1,1
672,007_S_6515_I1346240,92,ADNI_CN,Female,420643.672730,362288.0,49466.0,45770.0,33882.540,ADNI,NaN,NaN,1,1
673,003_S_1074_I912458,96,ADNI_AD_MCI,Female,407961.721732,344260.0,44911.0,57918.0,35343.520,ADNI,NaN,NaN,1,1